name: reharden

on:
  push:
  workflow_dispatch:

jobs:
  reharden:
    strategy:
      fail-fast: false
      matrix:
        project:
          - tt_um_3515_sequenceDetector
          - tt_um_4bit_cpu_with_fsm
          - tt_um_7seg_animated
          - tt_um_8bitALU
          - tt_um_8bit_cpu
          - tt_um_ADPCM_COMPRESSOR
          - tt_um_ALU
          - tt_um_ALU_DECODERS
          - tt_um_BoothMulti_hhrb98
          - tt_um_CDMA_Santiago
          - tt_um_CKPope_top
          - tt_um_CodHex7seg
          - tt_um_Counter_1_shivam
          - tt_um_DigitalClockTop
          - tt_um_FanCTRL_DomnikBrandstetter
          - tt_um_I2C_to_SPI
          - tt_um_LFSR_shivam
          - tt_um_MATTHIAS_M_PAL_TOP_WRAPPER
          - tt_um_MNSLab_BLDC
          - tt_um_MichaelBell_latch_mem
          - tt_um_MichaelBell_tinyQV
          - tt_um_PWM
          - tt_um_PWM_Controller
          - tt_um_PWM_Sine_UART
          - tt_um_QIF_8bit
          - tt_um_S2P
          - tt_um_SJ
          - tt_um_SteffenReith_ASGTop
          - tt_um_SteffenReith_PiMACTop
          - tt_um_UABCReloj
          - tt_um_Uart_Transciver
          - tt_um_adammaj
          - tt_um_advanced_counter
          - tt_um_aerox2_jrb8_computer
          - tt_um_aiju_8080
          - tt_um_alexsegura_pong
          - tt_um_alu
          - tt_um_ancho
          - tt_um_andrewtron3000
          - tt_um_andychip1_sn74169
          - tt_um_array_multiplier_hhrb98
          - tt_um_bit_ctrl
          - tt_um_bomba1
          - tt_um_calculator_muehlbb
          - tt_um_cejmu_riscv
          - tt_um_chatgpt_rsnn_paolaunisa
          - tt_um_chisel_hello_schoeberl
          - tt_um_chisel_pong
          - tt_um_cmerrill_pdm
          - tt_um_coloquinte_moosic
          - tt_um_couchand_cora16
          - tt_um_couchand_dual_deque
          - tt_um_csit_luks
          - tt_um_devinatkin_fastreadout
          - tt_um_dgkaminski
          - tt_um_dieroller_nathangross1
          - tt_um_digitaler_filter_rathmayr
          - tt_um_disp1
          - tt_um_dlmiles_muldiv8
          - tt_um_dlmiles_muldiv8_sky130faha
          - tt_um_dlmiles_poc_fskmodem_hdlctrx
          - tt_um_dr_skyler_clock
          - tt_um_drburke3_top
          - tt_um_drops
          - tt_um_dvxf_dj8
          - tt_um_ejfogleman_smsdac
          - tt_um_enieman
          - tt_um_entwurf_integrierter_schaltungen_hadner
          - tt_um_ericsmi_weste_problem_4_11
          - tt_um_exai_izhikevich_neuron
          - tt_um_factory_test
          - tt_um_faramire_gate_guesser
          - tt_um_faramire_stopwatch
          - tt_um_fdc_chip
          - tt_um_flappy_bird
          - tt_um_fountaincoder_top
          - tt_um_fpu
          - tt_um_frq_divider
          - tt_um_fstolzcode
          - tt_um_g3f
          - tt_um_gabejessil_timer
          - tt_um_gak25_8bit_cpu_ext
          - tt_um_gray_sobel
          - tt_um_haeuslermarkus_fir_filter
          - tt_um_histefan_top
          - tt_um_hpretl_tt06_tdc
          - tt_um_hpretl_tt06_tdc_v2
          - tt_um_hpretl_tt06_tempsens
          - tt_um_hsc_tdc
          - tt_um_hsc_tdc_buf
          - tt_um_hsc_tdc_mux
          - tt_um_i_tree_batzolislefteris
          - tt_um_ian_keypad_controller
          - tt_um_iron_violet_simon
          - tt_um_ja1tye_tiny_cpu
          - tt_um_jduchniewicz_prng
          - tt_um_jorgenkraghjakobsen_toi2s
          - tt_um_jv_sigdel
          - tt_um_kianV_rv32ima_uLinux_SoC
          - tt_um_koconnor_kstep
          - tt_um_ks_pyamnihc
          - tt_um_kwilke_cdc_fifo
          - tt_um_lancemitrex
          - tt_um_ledcontroller_Gatsch
          - tt_um_lipsi_schoeberl
          - tt_um_lisa
          - tt_um_liu3hao_rv32e_min_mcu
          - tt_um_lk_ans_top
          - tt_um_loco_choco
          - tt_um_lucaz97_monobit
          - tt_um_lucaz97_rng_tests
          - tt_um_mattvenn_rgb_mixer
          - tt_um_mayrmichael_wave_generator
          - tt_um_mbalestrini_usb_cdc_devices
          - tt_um_meiniKi_tt06_fazyrv_exotiny
          - tt_um_minibyte
          - tt_um_mitssdd
          - tt_um_motor
          - tt_um_moving_average_master
          - tt_um_mult_2b
          - tt_um_mw73_pmic
          - tt_um_neurocore
          - tt_um_nicklausthompson_twi_monitor
          - tt_um_noritsuna_i4004
          - tt_um_nubcore_default_tape
          - tt_um_obriensp_be8
          - tt_um_obriensp_be8_nomacro
          - tt_um_oscillating_bones
          - tt_um_otp_encryptor
          - tt_um_pckys_game
          - tt_um_petersn_micro1
          - tt_um_ppca
          - tt_um_ps2_morse_encoder_top
          - tt_um_qubitbytes_alive
          - tt_um_ram
          - tt_um_rejunity_1_58bit
          - tt_um_rejunity_fp4_mul_i8
          - tt_um_rgbled_decoder
          - tt_um_rng
          - tt_um_rng_3_lucaz97
          - tt_um_s1pu11i_simple_nco
          - tt_um_sanojn_tlv2556_interface
          - tt_um_sanojn_ttrpg_dice
          - tt_um_sap_1
          - tt_um_scorbetta_goa
          - tt_um_seven_segment_fun1
          - tt_um_shivam
          - tt_um_signed_unsigned_4x4_bit_multiplier
          - tt_um_silicon_tinytapeout_lm07
          - tt_um_simplez_rcoeurjoly
          - tt_um_soundgen
          - tt_um_spi_pwm_djuara
          - tt_um_spiff42_exp_led_pwm
          - tt_um_ss_register
          - tt_um_stepper
          - tt_um_thorkn_audiochip_v2
          - tt_um_timer_counter_UGM
          - tt_um_tiny_shader_mole99
          - tt_um_toivoh_retro_console
          - tt_um_tomkeddie_a
          - tt_um_tommythorn_4b_cpu_v2
          - tt_um_tommythorn_ncl_lfsr
          - tt_um_topTDC
          - tt_um_triple_watchdog
          - tt_um_urish_simon
          - tt_um_urish_spell
          - tt_um_voting_thingey
          - tt_um_wallace_hhrb98
          - tt_um_wokwi_384437973887503361
          - tt_um_wokwi_384711264596377601
          - tt_um_wokwi_384804985843168257
          - tt_um_wokwi_390913889347409921
          - tt_um_wokwi_392873974467527681
          - tt_um_wokwi_393815624518031361
          - tt_um_wokwi_394618582085551105
          - tt_um_wokwi_394640918790880257
          - tt_um_wokwi_394704587372210177
          - tt_um_wokwi_394707429798790145
          - tt_um_wokwi_394830069681034241
          - tt_um_wokwi_394888799427677185
          - tt_um_wokwi_394898807123828737
          - tt_um_wokwi_395034561853515777
          - tt_um_wokwi_395054466384583681
          - tt_um_wokwi_395054508867644417
          - tt_um_wokwi_395054564978002945
          - tt_um_wokwi_395054820631340033
          - tt_um_wokwi_395054823569451009
          - tt_um_wokwi_395054823837887489
          - tt_um_wokwi_395055035944909825
          - tt_um_wokwi_395055341723330561
          - tt_um_wokwi_395055351144787969
          - tt_um_wokwi_395055359324730369
          - tt_um_wokwi_395055455727667201
          - tt_um_wokwi_395055722430895105
          - tt_um_wokwi_395058308283408385
          - tt_um_wokwi_395061443288867841
          - tt_um_wokwi_395134712676183041
          - tt_um_wokwi_395142547244224513
          - tt_um_wokwi_395179352683141121
          - tt_um_wokwi_395263962779770881
          - tt_um_wokwi_395355133883896833
          - tt_um_wokwi_395357890431011841
          - tt_um_wokwi_395414987024660481
          - tt_um_wokwi_395444977868278785
          - tt_um_wokwi_395514572866576385
          - tt_um_wokwi_395522292785089537
          - tt_um_wokwi_395567106413190145
          - tt_um_wokwi_395599496098067457
          - tt_um_wokwi_395614106833794049
          - tt_um_wokwi_395615790979120129
          - tt_um_wokwi_395618714068432897
          - tt_um_wuehr1999_servotester
          - tt_um_zhwa_rgb_mixer
    runs-on: ubuntu-latest
    env:
      OPENLANE_TAG: 2024.04.02
      OPENLANE_IMAGE_NAME: efabless/openlane:2024.04.02
      OPENLANE_ROOT: /home/runner/openlane
      PDK_ROOT: /home/runner/pdk
      PDK: sky130A
      # Tool versions:
      MAGIC_VERSION: 8.3.473
      KLAYOUT_VERSION: 0.29.0
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Checkout tt-support-tools repo
        uses: actions/checkout@v4
        with:
          repository: tinytapeout/tt-support-tools
          path: tt
          ref: tt06

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install OpenLane
        run: |
          git clone --depth=1 --branch $OPENLANE_TAG https://github.com/The-OpenROAD-Project/OpenLane.git $OPENLANE_ROOT
          cd $OPENLANE_ROOT
          make
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Make GDS with OpenLane
        working-directory: ${{ matrix.project }}
        run: |
          mkdir -p tt/def
          cp ../tt/def/*.def tt/def/
          docker run --rm -v $OPENLANE_ROOT:/openlane \
              -v $PDK_ROOT:$PDK_ROOT -v $(pwd):/work -e PDK=$PDK -e PDK_ROOT=$PDK_ROOT \
              -u $(id -u $USER):$(id -g $USER) $OPENLANE_IMAGE_NAME \
              /bin/bash -c "./flow.tcl -overwrite -design /work/src -run_path /work/runs -tag wokwi"

          if ! grep -q "\[SUCCESS\]: Flow complete." runs/wokwi/openlane.log; then
            exit 1
          fi

          # Fail if issue_reproducible directory exists
          if [ -d "runs/wokwi/issue_reproducible" ]; then
            exit 1
          fi

      - name: Install magic-vlsi
        run: |
          sudo apt-get update && sudo apt-get install -y build-essential git csh libcairo2-dev tcl-dev tk-dev
          git clone --branch ${MAGIC_VERSION} https://github.com/RTimothyEdwards/magic
          cd magic && ./configure --with-cairo=no --disable-readline --without-x && make && sudo make install

      - name: Install klayout
        run: |
          wget https://www.klayout.org/downloads/Ubuntu-22/klayout_${KLAYOUT_VERSION}-1_amd64.deb
          sudo apt-get update
          sudo apt-get install -y ./klayout_${KLAYOUT_VERSION}-1_amd64.deb

      - name: Run tiny tapeout prechecks
        working-directory: tt/precheck
        run: |
          set -o pipefail
          pip install -r requirements.txt
          python precheck.py --gds $GDS
          cp -R reports ${PROJECT_DIR}/precheck
          cat reports/results.md | tee -a $GITHUB_STEP_SUMMARY
        env:
          PROJECT_DIR: ${{ github.workspace }}/${{ matrix.project }}
          GDS: ${{ github.workspace }}/${{ matrix.project }}/runs/wokwi/results/final/gds/${{ matrix.project }}.gds

      - name: Publish build logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: GDS_${{ matrix.project }}
          path: |
            ${{ matrix.project }}/runs/*
            ${{ matrix.project }}/precheck/*
